#@summary: Supported version of RDP
#@see: http://msdn.microsoft.com/en-us/library/cc240510.aspx
versions:
  RDP_VERSION_4: 0x00080001
  RDP_VERSION_5_PLUS: 0x00080004

#@summary: GCC conference messages
#@see: http://msdn.microsoft.com/en-us/library/cc240509.aspx
messageType:
  #server -> client
  SC_CORE: 0x0C01
  SC_SECURITY: 0x0C02
  SC_NET: 0x0C03
  #client -> server
  CS_CORE: 0xC001
  CS_SECURITY: 0xC002
  CS_NET: 0xC003
  CS_CLUSTER: 0xC004
  CS_MONITOR: 0xC005

#@summary: Channel id of main channels use in RDP
channel:
  MCS_GLOBAL_CHANNEL: 1003
  MCS_USERCHANNEL_BASE: 1001


#@summary: Different type of capabilities
#@see: http://msdn.microsoft.com/en-us/library/cc240486.aspx
capsType:
  CAPSTYPE_GENERAL: 0x0001
  CAPSTYPE_BITMAP: 0x0002
  CAPSTYPE_ORDER: 0x0003
  CAPSTYPE_BITMAPCACHE: 0x0004
  CAPSTYPE_CONTROL: 0x0005
  CAPSTYPE_ACTIVATION: 0x0007
  CAPSTYPE_POINTER: 0x0008
  CAPSTYPE_SHARE: 0x0009
  CAPSTYPE_COLORCACHE: 0x000A
  CAPSTYPE_SOUND: 0x000C
  CAPSTYPE_INPUT: 0x000D
  CAPSTYPE_FONT: 0x000E
  CAPSTYPE_BRUSH: 0x000F
  CAPSTYPE_GLYPHCACHE: 0x0010
  CAPSTYPE_OFFSCREENCACHE: 0x0011
  CAPSTYPE_BITMAPCACHE_HOSTSUPPORT: 0x0012
  CAPSTYPE_BITMAPCACHE_REV2: 0x0013
  CAPSTYPE_VIRTUALCHANNEL: 0x0014
  CAPSTYPE_DRAWNINEGRIDCACHE: 0x0015
  CAPSTYPE_DRAWGDIPLUS: 0x0016
  CAPSTYPE_RAIL: 0x0017
  CAPSTYPE_WINDOW: 0x0018
  CAPSETTYPE_COMPDESK: 0x0019
  CAPSETTYPE_MULTIFRAGMENTUPDATE: 0x001A
  CAPSETTYPE_LARGE_POINTER: 0x001B
  CAPSETTYPE_SURFACE_COMMANDS: 0x001C
  CAPSETTYPE_BITMAP_CODECS: 0x001D
  CAPSSETTYPE_FRAME_ACKNOWLEDGE: 0x001E


#summary: Use in order capability
#see: http://msdn.microsoft.com/en-us/library/cc240556.aspx
orderFlag:
  NEGOTIATEORDERSUPPORT: 0x0002
  ZEROBOUNDSDELTASSUPPORT: 0x0008
  COLORINDEXSUPPORT: 0x0020
  SOLIDPATTERNBRUSHONLY: 0x0040
  ORDERFLAGS_EXTRA_FLAGS: 0x0080

#summary: Brush support of client
#see: http://msdn.microsoft.com/en-us/library/cc240564.aspx
brushSupport:
  BRUSH_DEFAULT: 0x00000000
  BRUSH_COLOR_8x8: 0x00000001
  BRUSH_COLOR_FULL: 0x00000002

#summary: Use by glyph order
#see: http://msdn.microsoft.com/en-us/library/cc240565.aspx
glyphSupport:
  GLYPH_SUPPORT_NONE: 0x0000
  GLYPH_SUPPORT_PARTIAL: 0x0001
  GLYPH_SUPPORT_FULL: 0x0002
  GLYPH_SUPPORT_ENCODE: 0x0003

#summary: Use to determine offscreen cache level supported
#see: http://msdn.microsoft.com/en-us/library/cc240550.aspx
offScreenSupport:
  VALUE_FALSE: 0x00000000
  VALUE_TRUE: 0x00000001

#summary: Use to determine virtual channel compression
#see: http://msdn.microsoft.com/en-us/library/cc240551.aspx
virtualChannelCompression:
  VCCAPS_NO_COMPR: 0x00000000
  VCCAPS_COMPR_SC: 0x00000001
  VCCAPS_COMPR_CS_8K: 0x00000002

#summary: Use in sound capability to inform it
#see: http://msdn.microsoft.com/en-us/library/cc240552.aspx
soundCapability:
  NONE: 0x0000
  SOUND_BEEPS_FLAG: 0x0001

#summary: Use in general capability
#see: http://msdn.microsoft.com/en-us/library/cc240549.aspx
majorType:
  OSMAJORTYPE_UNSPECIFIED: 0x0000
  OSMAJORTYPE_WINDOWS: 0x0001
  OSMAJORTYPE_OS2: 0x0002
  OSMAJORTYPE_MACINTOSH: 0x0003
  OSMAJORTYPE_UNIX: 0x0004
  OSMAJORTYPE_IOS: 0x0005
  OSMAJORTYPE_OSX: 0x0006
  OSMAJORTYPE_ANDROID: 0x0007

#summary: Use in general capability
#see: http://msdn.microsoft.com/en-us/library/cc240549.aspx
minorType:
  OSMINORTYPE_UNSPECIFIED: 0x0000
  OSMINORTYPE_WINDOWS_31X: 0x0001
  OSMINORTYPE_WINDOWS_95: 0x0002
  OSMINORTYPE_WINDOWS_NT: 0x0003
  OSMINORTYPE_OS2_V21: 0x0004
  OSMINORTYPE_POWER_PC: 0x0005
  OSMINORTYPE_MACINTOSH: 0x0006
  OSMINORTYPE_NATIVE_XSERVER: 0x0007
  OSMINORTYPE_PSEUDO_XSERVER: 0x0008
  OSMINORTYPE_WINDOWS_RT: 0x0009

#summary: Use in general capability
#see: http://msdn.microsoft.com/en-us/library/cc240549.aspx
generalExtraFlag:
  FASTPATH_OUTPUT_SUPPORTED: 0x0001
  NO_BITMAP_COMPRESSION_HDR: 0x0400
  LONG_CREDENTIALS_SUPPORTED: 0x0004
  AUTORECONNECT_SUPPORTED: 0x0008
  ENC_SALTED_CHECKSUM: 0x0010

boolean:
  FALSE: 0x00
  TRUE: 0x01

#summary: Drawing orders supported
#Use in order capability
#see: http://msdn.microsoft.com/en-us/library/cc240556.aspx
order:
  TS_NEG_DSTBLT_INDEX: 0x00
  TS_NEG_PATBLT_INDEX: 0x01
  TS_NEG_SCRBLT_INDEX: 0x02
  TS_NEG_MEMBLT_INDEX: 0x03
  TS_NEG_MEM3BLT_INDEX: 0x04
  TS_NEG_DRAWNINEGRID_INDEX: 0x07
  TS_NEG_LINETO_INDEX: 0x08
  TS_NEG_MULTI_DRAWNINEGRID_INDEX: 0x09
  TS_NEG_SAVEBITMAP_INDEX: 0x0B
  TS_NEG_MULTIDSTBLT_INDEX: 0x0F
  TS_NEG_MULTIPATBLT_INDEX: 0x10
  TS_NEG_MULTISCRBLT_INDEX: 0x11
  TS_NEG_MULTIOPAQUERECT_INDEX: 0x12
  TS_NEG_FAST_INDEX_INDEX: 0x13
  TS_NEG_POLYGON_SC_INDEX: 0x14
  TS_NEG_POLYGON_CB_INDEX: 0x15
  TS_NEG_POLYLINE_INDEX: 0x16
  TS_NEG_FAST_GLYPH_INDEX: 0x18
  TS_NEG_ELLIPSE_SC_INDEX: 0x19
  TS_NEG_ELLIPSE_CB_INDEX: 0x1A
  TS_NEG_INDEX_INDEX: 0x1B

#summary: Extension orders
#Use in order capability
orderEx:
  ORDERFLAGS_EX_CACHE_BITMAP_REV3_SUPPORT: 0x0002
  ORDERFLAGS_EX_ALTSEC_FRAME_MARKER_SUPPORT: 0x0004

#summary: Input flag use in input capability
#see:  http://msdn.microsoft.com/en-us/library/cc240563.aspx
inputFlag:
  INPUT_FLAG_SCANCODES: 0x0001
  INPUT_FLAG_MOUSEX: 0x0004
  INPUT_FLAG_FASTPATH_INPUT: 0x0008
  INPUT_FLAG_UNICODE: 0x0010
  INPUT_FLAG_FASTPATH_INPUT2: 0x0020
  INPUT_FLAG_UNUSED1: 0x0040
  INPUT_FLAG_UNUSED2: 0x0080
  TS_INPUT_FLAG_MOUSE_HWHEEL: 0x0100


#@see: http://msdn.microsoft.com/en-us/library/cc240521.aspx
certificateType:
  CERT_CHAIN_VERSION_1: 0x00000001
  CERT_CHAIN_VERSION_2: 0x00000002

#IPv4 or IPv6 address style
afInet:
  AF_INET: 0x00002
  AF_INET6: 0x0017


#Client capabilities informations
infoFlag:
  INFO_MOUSE: 0x00000001
  INFO_DISABLECTRLALTDEL: 0x00000002
  INFO_AUTOLOGON: 0x00000008
  INFO_UNICODE: 0x00000010
  INFO_MAXIMIZESHELL: 0x00000020
  INFO_LOGONNOTIFY: 0x00000040
  INFO_COMPRESSION: 0x00000080
  INFO_ENABLEWINDOWSKEY: 0x00000100
  INFO_REMOTECONSOLEAUDIO: 0x00002000
  INFO_FORCE_ENCRYPTED_CS_PDU: 0x00004000
  INFO_RAIL: 0x00008000
  INFO_LOGONERRORS: 0x00010000
  INFO_MOUSE_HAS_WHEEL: 0x00020000
  INFO_PASSWORD_IS_SC_PIN: 0x00040000
  INFO_NOAUDIOPLAYBACK: 0x00080000
  INFO_USING_SAVED_CREDS: 0x00100000
  INFO_AUDIOCAPTURE: 0x00200000
  INFO_VIDEO_DISABLE: 0x00400000
  INFO_CompressionTypeMask: 0x00001E00

#@summary: Depth color
#@see: http://msdn.microsoft.com/en-us/library/cc240510.aspx
colorDepth:
  RNS_UD_COLOR_8BPP: 0xCA01
  RNS_UD_COLOR_16BPP_555: 0xCA02
  RNS_UD_COLOR_16BPP_565: 0xCA03
  RNS_UD_COLOR_24BPP: 0xCA04

sequence:
  RNS_UD_SAS_DEL: 0xAA03

#@summary: Keyboard layout definition
#@see: http://technet.microsoft.com/en-us/library/cc766503%28WS.10%29.aspx
keyboardLayout:
  ARABIC: 0x00000401
  BULGARIAN: 0x00000402
  CHINESE_US_KEYBOARD: 0x00000404
  CZECH: 0x00000405
  DANISH: 0x00000406
  GERMAN: 0x00000407
  GREEK: 0x00000408
  US: 0x00000409
  SPANISH: 0x0000040a
  FINNISH: 0x0000040b
  FRENCH: 0x0000040c
  HEBREW: 0x0000040d
  HUNGARIAN: 0x0000040e
  ICELANDIC: 0x0000040f
  ITALIAN: 0x00000410
  JAPANESE: 0x00000411
  KOREAN: 0x00000412
  DUTCH: 0x00000413
  NORWEGIAN: 0x00000414

#@summary: High color of client
#@see: http://msdn.microsoft.com/en-us/library/cc240510.aspx
highColor:
  HIGH_COLOR_4BPP: 0x0004
  HIGH_COLOR_8BPP: 0x0008
  HIGH_COLOR_15BPP: 0x000f
  HIGH_COLOR_16BPP: 0x0010
  HIGH_COLOR_24BPP: 0x0018

#@summary: Supported depth flag
#@see: http://msdn.microsoft.com/en-us/library/cc240510.aspx
support:
  RNS_UD_24BPP_SUPPORT: 0x0001
  RNS_UD_16BPP_SUPPORT: 0x0002
  RNS_UD_15BPP_SUPPORT: 0x0004
  RNS_UD_32BPP_SUPPORT: 0x0008

#@summary: For more details on each flags click above
#@see: http://msdn.microsoft.com/en-us/library/cc240510.aspx
capabilityFlag:
  RNS_UD_CS_SUPPORT_ERRINFO_PDU: 0x0001
  RNS_UD_CS_WANT_32BPP_SESSION: 0x0002
  RNS_UD_CS_SUPPORT_STATUSINFO_PDU: 0x0004
  RNS_UD_CS_STRONG_ASYMMETRIC_KEYS: 0x0008
  RNS_UD_CS_UNUSED: 0x0010
  RNS_UD_CS_VALID_CONNECTION_TYPE: 0x0020
  RNS_UD_CS_SUPPORT_MONITOR_LAYOUT_PDU: 0x0040
  RNS_UD_CS_SUPPORT_NETCHAR_AUTODETECT: 0x0080
  RNS_UD_CS_SUPPORT_DYNVC_GFX_PROTOCOL: 0x0100
  RNS_UD_CS_SUPPORT_DYNAMIC_TIME_ZONE: 0x0200
  RNS_UD_CS_SUPPORT_HEARTBEAT_PDU: 0x0400

#@summary: Encryption methods supported
#@see: http://msdn.microsoft.com/en-us/library/cc240511.aspx
encryptionMethod:
  ENCRYPTION_FLAG_40BIT: 0x00000001
  ENCRYPTION_FLAG_128BIT: 0x00000002
  ENCRYPTION_FLAG_56BIT: 0x00000008
  FIPS_ENCRYPTION_FLAG: 0x00000010

#@summary: Channel id of main channels use in RDP
channelId:
  MCS_GLOBAL_CHANNEL: 1003
  MCS_USERCHANNEL_BASE: 1001

#@summary: Domain MCS PDU header
domainMCSPdu:
  ERECT_DOMAIN_REQUEST: 1
  DISCONNECT_PROVIDER_ULTIMATUM: 8
  ATTACH_USER_REQUEST: 10
  ATTACH_USER_CONFIRM: 11
  CHANNEL_JOIN_REQUEST: 14
  CHANNEL_JOIN_CONFIRM: 15
  SEND_DATA_REQUEST: 25
  SEND_DATA_INDICATION: 26

#@summary: Keyboard type
#@see: IBM_101_102_KEYS is the most common keyboard type
keyboardType:
  IBM_PC_XT_83_KEY: 0x00000001
  OLIVETTI: 0x00000002
  IBM_PC_AT_84_KEY: 0x00000003
  IBM_101_102_KEYS: 0x00000004
  NOKIA_1050: 0x00000005
  NOKIA_9140: 0x00000006
  JAPANESE: 0x00000007

#@summary: Protocols available for x224 layer
#@see: https://msdn.microsoft.com/en-us/library/cc240500.aspx
protocols:
  PROTOCOL_RDP: 0x00000000
  PROTOCOL_SSL: 0x00000001
  PROTOCOL_HYBRID: 0x00000002
  PROTOCOL_HYBRID_EX: 0x00000008

#@summary: Message type
messageTypeX224:
  X224_TPDU_CONNECTION_REQUEST: 0xE0
  X224_TPDU_DESTINATION_REFERENCE: 0x00
  X224_TPDU_SOURCE_REFERENCE: 0x00
  X224_TPDU_CLASS_OPTION: 0x00
  X224_TPDU_CONNECTION_CONFIRM: 0xD0
  X224_TPDU_DISCONNECT_REQUEST: 0x80
  X224_TPDU_DATA: 0xF0
  X224_TPDU_ERROR: 0x70

#@summary: Negotiation header
negotiationType:
  TYPE_RDP_NEG_REQ: 0x01
  TYPE_RDP_NEG_RSP: 0x02
  TYPE_RDP_NEG_FAILURE: 0x03

tpkt:
  VERSION: 0x03
  RESERVED: 0x00